#!/bin/bash
cp -f bin/jbchlist /usr/local/bin/
cp -f bin/jbrstart /usr/local/bin/
cp -f bin/jbrecord /usr/local/bin/
cp -f bin/jbcomp /usr/local/bin/
cp -rf etc/jb /etc/
cp -f bin/route-enable /usr/local/bin/
cp -rf usr/lib/systemd/system /usr/lib/systemd/
systemctl enable jb.service
systemctl enable jb.timer
systemctl start jb.service
systemctl start jb.timer
