#!/bin/bash
CODE_MACHINE='224.2.2.0'
#LOG='/var/log/r.log'

#if [ ! -f ${LOG} ]; then
#    touch ${LOG}
#fi

res=$(route | grep ${CODE_MACHINE})
#echo "$(date +%Y-%m-%dT%H:%M:%S): filter router: ${res}" >> ${LOG}
des=$(echo ${res} | cut -d ' ' -f1)
#echo "$(date +%Y-%m-%dT%H:%M:%S): filter des: -${des}-" >> ${LOG}


#if [ ${des} != ${CODE_MACHINE} ]; then
#echo "$(date +%Y-%m-%dT%H:%M:%S): reload router"
#route add -net 224.2.2.0 netmask 255.255.255.0 gw 192.168.0.1 dev enp3s0
route add -net 224.2.2.0 netmask 255.255.255.0 dev enp5s0f1
#route del -net default netmask 0.0.0.0 gw 192.168.0.1
#else
#echo "$(date +%Y-%m-%dT%H:%M:%S): route ok" >> ${LOG}
#fi

